// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package replica_key

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if ((a == nil && b != nil) ||
			(a != nil && b == nil)) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.BypassPolicyLockoutSafetyCheck, b.ko.Spec.BypassPolicyLockoutSafetyCheck) {
		delta.Add("Spec.BypassPolicyLockoutSafetyCheck", a.ko.Spec.BypassPolicyLockoutSafetyCheck, b.ko.Spec.BypassPolicyLockoutSafetyCheck)
	} else if a.ko.Spec.BypassPolicyLockoutSafetyCheck != nil && b.ko.Spec.BypassPolicyLockoutSafetyCheck != nil {
		if *a.ko.Spec.BypassPolicyLockoutSafetyCheck != *b.ko.Spec.BypassPolicyLockoutSafetyCheck {
			delta.Add("Spec.BypassPolicyLockoutSafetyCheck", a.ko.Spec.BypassPolicyLockoutSafetyCheck, b.ko.Spec.BypassPolicyLockoutSafetyCheck)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.KeyID, b.ko.Spec.KeyID) {
		delta.Add("Spec.KeyID", a.ko.Spec.KeyID, b.ko.Spec.KeyID)
	} else if a.ko.Spec.KeyID != nil && b.ko.Spec.KeyID != nil {
		if *a.ko.Spec.KeyID != *b.ko.Spec.KeyID {
			delta.Add("Spec.KeyID", a.ko.Spec.KeyID, b.ko.Spec.KeyID)
		}
	}
	if !reflect.DeepEqual(a.ko.Spec.KeyRef, b.ko.Spec.KeyRef) {
		delta.Add("Spec.KeyRef", a.ko.Spec.KeyRef, b.ko.Spec.KeyRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Policy, b.ko.Spec.Policy) {
		delta.Add("Spec.Policy", a.ko.Spec.Policy, b.ko.Spec.Policy)
	} else if a.ko.Spec.Policy != nil && b.ko.Spec.Policy != nil {
		if *a.ko.Spec.Policy != *b.ko.Spec.Policy {
			delta.Add("Spec.Policy", a.ko.Spec.Policy, b.ko.Spec.Policy)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ReplicaRegion, b.ko.Spec.ReplicaRegion) {
		delta.Add("Spec.ReplicaRegion", a.ko.Spec.ReplicaRegion, b.ko.Spec.ReplicaRegion)
	} else if a.ko.Spec.ReplicaRegion != nil && b.ko.Spec.ReplicaRegion != nil {
		if *a.ko.Spec.ReplicaRegion != *b.ko.Spec.ReplicaRegion {
			delta.Add("Spec.ReplicaRegion", a.ko.Spec.ReplicaRegion, b.ko.Spec.ReplicaRegion)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
