// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package replica_key

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/kms"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/kms/types"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/kms-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.ReplicaKey{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	return rm.customFind(ctx, r)
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.ReplicateKeyOutput
	_ = resp
	resp, err = rm.sdkapi.ReplicateKey(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "ReplicateKey", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ReplicaKeyMetadata != nil {
		f0 := &svcapitypes.KeyMetadata{}
		if resp.ReplicaKeyMetadata.AWSAccountId != nil {
			f0.AWSAccountID = resp.ReplicaKeyMetadata.AWSAccountId
		}
		if resp.ReplicaKeyMetadata.Arn != nil {
			f0.ARN = resp.ReplicaKeyMetadata.Arn
		}
		if resp.ReplicaKeyMetadata.CloudHsmClusterId != nil {
			f0.CloudHsmClusterID = resp.ReplicaKeyMetadata.CloudHsmClusterId
		}
		if resp.ReplicaKeyMetadata.CreationDate != nil {
			f0.CreationDate = &metav1.Time{*resp.ReplicaKeyMetadata.CreationDate}
		}
		if resp.ReplicaKeyMetadata.CustomKeyStoreId != nil {
			f0.CustomKeyStoreID = resp.ReplicaKeyMetadata.CustomKeyStoreId
		}
		if resp.ReplicaKeyMetadata.DeletionDate != nil {
			f0.DeletionDate = &metav1.Time{*resp.ReplicaKeyMetadata.DeletionDate}
		}
		if resp.ReplicaKeyMetadata.Description != nil {
			f0.Description = resp.ReplicaKeyMetadata.Description
		}
		f0.Enabled = &resp.ReplicaKeyMetadata.Enabled
		if resp.ReplicaKeyMetadata.EncryptionAlgorithms != nil {
			f0f8 := []*string{}
			for _, f0f8iter := range resp.ReplicaKeyMetadata.EncryptionAlgorithms {
				var f0f8elem *string
				f0f8elem = aws.String(string(f0f8iter))
				f0f8 = append(f0f8, f0f8elem)
			}
			f0.EncryptionAlgorithms = f0f8
		}
		if resp.ReplicaKeyMetadata.ExpirationModel != "" {
			f0.ExpirationModel = aws.String(string(resp.ReplicaKeyMetadata.ExpirationModel))
		}
		if resp.ReplicaKeyMetadata.KeyId != nil {
			f0.KeyID = resp.ReplicaKeyMetadata.KeyId
		}
		if resp.ReplicaKeyMetadata.KeyManager != "" {
			f0.KeyManager = aws.String(string(resp.ReplicaKeyMetadata.KeyManager))
		}
		if resp.ReplicaKeyMetadata.KeySpec != "" {
			f0.KeySpec = aws.String(string(resp.ReplicaKeyMetadata.KeySpec))
		}
		if resp.ReplicaKeyMetadata.KeyState != "" {
			f0.KeyState = aws.String(string(resp.ReplicaKeyMetadata.KeyState))
		}
		if resp.ReplicaKeyMetadata.KeyUsage != "" {
			f0.KeyUsage = aws.String(string(resp.ReplicaKeyMetadata.KeyUsage))
		}
		if resp.ReplicaKeyMetadata.MacAlgorithms != nil {
			f0f15 := []*string{}
			for _, f0f15iter := range resp.ReplicaKeyMetadata.MacAlgorithms {
				var f0f15elem *string
				f0f15elem = aws.String(string(f0f15iter))
				f0f15 = append(f0f15, f0f15elem)
			}
			f0.MacAlgorithms = f0f15
		}
		if resp.ReplicaKeyMetadata.MultiRegion != nil {
			f0.MultiRegion = resp.ReplicaKeyMetadata.MultiRegion
		}
		if resp.ReplicaKeyMetadata.MultiRegionConfiguration != nil {
			f0f17 := &svcapitypes.MultiRegionConfiguration{}
			if resp.ReplicaKeyMetadata.MultiRegionConfiguration.MultiRegionKeyType != "" {
				f0f17.MultiRegionKeyType = aws.String(string(resp.ReplicaKeyMetadata.MultiRegionConfiguration.MultiRegionKeyType))
			}
			if resp.ReplicaKeyMetadata.MultiRegionConfiguration.PrimaryKey != nil {
				f0f17f1 := &svcapitypes.MultiRegionKey{}
				if resp.ReplicaKeyMetadata.MultiRegionConfiguration.PrimaryKey.Arn != nil {
					f0f17f1.ARN = resp.ReplicaKeyMetadata.MultiRegionConfiguration.PrimaryKey.Arn
				}
				if resp.ReplicaKeyMetadata.MultiRegionConfiguration.PrimaryKey.Region != nil {
					f0f17f1.Region = resp.ReplicaKeyMetadata.MultiRegionConfiguration.PrimaryKey.Region
				}
				f0f17.PrimaryKey = f0f17f1
			}
			if resp.ReplicaKeyMetadata.MultiRegionConfiguration.ReplicaKeys != nil {
				f0f17f2 := []*svcapitypes.MultiRegionKey{}
				for _, f0f17f2iter := range resp.ReplicaKeyMetadata.MultiRegionConfiguration.ReplicaKeys {
					f0f17f2elem := &svcapitypes.MultiRegionKey{}
					if f0f17f2iter.Arn != nil {
						f0f17f2elem.ARN = f0f17f2iter.Arn
					}
					if f0f17f2iter.Region != nil {
						f0f17f2elem.Region = f0f17f2iter.Region
					}
					f0f17f2 = append(f0f17f2, f0f17f2elem)
				}
				f0f17.ReplicaKeys = f0f17f2
			}
			f0.MultiRegionConfiguration = f0f17
		}
		if resp.ReplicaKeyMetadata.Origin != "" {
			f0.Origin = aws.String(string(resp.ReplicaKeyMetadata.Origin))
		}
		if resp.ReplicaKeyMetadata.PendingDeletionWindowInDays != nil {
			pendingDeletionWindowInDaysCopy := int64(*resp.ReplicaKeyMetadata.PendingDeletionWindowInDays)
			f0.PendingDeletionWindowInDays = &pendingDeletionWindowInDaysCopy
		}
		if resp.ReplicaKeyMetadata.SigningAlgorithms != nil {
			f0f20 := []*string{}
			for _, f0f20iter := range resp.ReplicaKeyMetadata.SigningAlgorithms {
				var f0f20elem *string
				f0f20elem = aws.String(string(f0f20iter))
				f0f20 = append(f0f20, f0f20elem)
			}
			f0.SigningAlgorithms = f0f20
		}
		if resp.ReplicaKeyMetadata.ValidTo != nil {
			f0.ValidTo = &metav1.Time{*resp.ReplicaKeyMetadata.ValidTo}
		}
		ko.Status.ReplicaKeyMetadata = f0
	} else {
		ko.Status.ReplicaKeyMetadata = nil
	}
	if resp.ReplicaPolicy != nil {
		ko.Status.ReplicaPolicy = resp.ReplicaPolicy
	} else {
		ko.Status.ReplicaPolicy = nil
	}
	if resp.ReplicaTags != nil {
		f2 := []*svcapitypes.Tag{}
		for _, f2iter := range resp.ReplicaTags {
			f2elem := &svcapitypes.Tag{}
			if f2iter.TagKey != nil {
				f2elem.TagKey = f2iter.TagKey
			}
			if f2iter.TagValue != nil {
				f2elem.TagValue = f2iter.TagValue
			}
			f2 = append(f2, f2elem)
		}
		ko.Status.ReplicaTags = f2
	} else {
		ko.Status.ReplicaTags = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.ReplicateKeyInput, error) {
	res := &svcsdk.ReplicateKeyInput{}

	if r.ko.Spec.BypassPolicyLockoutSafetyCheck != nil {
		res.BypassPolicyLockoutSafetyCheck = *r.ko.Spec.BypassPolicyLockoutSafetyCheck
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.KeyID != nil {
		res.KeyId = r.ko.Spec.KeyID
	}
	if r.ko.Spec.Policy != nil {
		res.Policy = r.ko.Spec.Policy
	}
	if r.ko.Spec.ReplicaRegion != nil {
		res.ReplicaRegion = r.ko.Spec.ReplicaRegion
	}
	if r.ko.Spec.Tags != nil {
		f5 := []svcsdktypes.Tag{}
		for _, f5iter := range r.ko.Spec.Tags {
			f5elem := &svcsdktypes.Tag{}
			if f5iter.TagKey != nil {
				f5elem.TagKey = f5iter.TagKey
			}
			if f5iter.TagValue != nil {
				f5elem.TagValue = f5iter.TagValue
			}
			f5 = append(f5, *f5elem)
		}
		res.Tags = f5
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.updateNotSupported(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.ScheduleKeyDeletionOutput
	_ = resp
	resp, err = rm.sdkapi.ScheduleKeyDeletion(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "ScheduleKeyDeletion", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.ScheduleKeyDeletionInput, error) {
	res := &svcsdk.ScheduleKeyDeletionInput{}

	if r.ko.Spec.KeyID != nil {
		res.KeyId = r.ko.Spec.KeyID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.ReplicaKey,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
