// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ReplicaKeySpec defines the desired state of ReplicaKey.
//
// ReplicaKey represents a replica of a multi-Region primary key in AWS KMS.
// Replica keys allow you to use the same key material in multiple AWS Regions.
type ReplicaKeySpec struct {

	// Skips ("bypasses") the key policy lockout safety check. The default value
	// is false.
	//
	// Setting this value to true increases the risk that the KMS key becomes unmanageable.
	// Do not set this value to true indiscriminately.
	//
	// For more information, see Default key policy (https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html#prevent-unmanageable-key)
	// in the Key Management Service Developer Guide.
	//
	// Use this parameter only when you intend to prevent the principal that is
	// making the request from making a subsequent PutKeyPolicy (https://docs.aws.amazon.com/kms/latest/APIReference/API_PutKeyPolicy.html)
	// request on the KMS key.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	BypassPolicyLockoutSafetyCheck *bool `json:"bypassPolicyLockoutSafetyCheck,omitempty"`
	// A description of the KMS key. Use a description that helps you decide whether
	// the KMS key is appropriate for a task. The default value is an empty string
	// (no description).
	//
	// Do not include confidential or sensitive information in this field. This
	// field may be displayed in plaintext in CloudTrail logs and other output.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	Description *string `json:"description,omitempty"`
	// Identifies the multi-Region primary key that is being replicated. To determine
	// whether a KMS key is a multi-Region primary key, use the DescribeKey operation
	// to check the value of the MultiRegionKeyType property.
	//
	// Specify the key ID or key ARN of a multi-Region primary key.
	//
	// For example:
	//
	//    * Key ID: mrk-1234abcd12ab34cd56ef1234567890ab
	//
	//    * Key ARN: arn:aws:kms:us-east-2:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab
	//
	// To get the key ID and key ARN for a KMS key, use ListKeys or DescribeKey.
	// +kubebuilder:validation:Required
	KeyID  *string                                  `json:"keyID"`
	KeyRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"keyRef,omitempty"`
	// The key policy to attach to the KMS key.
	//
	// If you provide a key policy, it must meet the following criteria:
	//
	//    * The key policy must allow the calling principal to make a subsequent
	//    PutKeyPolicy request on the KMS key. This reduces the risk that the KMS
	//    key becomes unmanageable. For more information, see Default key policy
	//    (https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html#prevent-unmanageable-key)
	//    in the Key Management Service Developer Guide. (To omit this condition,
	//    set BypassPolicyLockoutSafetyCheck to true.)
	//
	//    * Each statement in the key policy must contain one or more principals.
	//    The principals in the key policy must exist and be visible to KMS. When
	//    you create a new Amazon Web Services principal, you might need to enforce
	//    a delay before including the new principal in a key policy because the
	//    new principal might not be immediately visible to KMS. For more information,
	//    see Changes that I make are not always immediately visible (https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_general.html#troubleshoot_general_eventual-consistency)
	//    in the Amazon Web Services Identity and Access Management User Guide.
	//
	// If you do not provide a key policy, KMS attaches a default key policy to
	// the KMS key. For more information, see Default key policy (https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html#key-policy-default)
	// in the Key Management Service Developer Guide.
	//
	// The key policy size quota is 32 kilobytes (32768 bytes).
	//
	// Regex Pattern: `^[\u0009\u000A\u000D\u0020-\u00FF]+$`
	Policy *string `json:"policy,omitempty"`
	// The AWS Region of the new replica key.
	//
	// Enter the Region ID, such as us-east-1 or ap-southeast-2. For a list of AWS
	// Regions in which AWS KMS is supported, see AWS KMS service endpoints (https://docs.aws.amazon.com/general/latest/gr/kms.html#kms_region)
	// in the Amazon Web Services General Reference.
	//
	// The Region of the replica must be different than the Region of the primary key.
	// You cannot create a replica key in the same Region as its primary key.
	//
	// The replica must be in the same AWS partition as its primary key. For example,
	// you cannot replicate a key from the aws partition to the aws-gov partition.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	ReplicaRegion *string `json:"replicaRegion"`
	// Assigns one or more tags to the replica key. Use this parameter to tag the
	// replica key when it is created. To tag an existing KMS key, use the TagResource
	// operation.
	//
	// Do not include confidential or sensitive information in this field. This
	// field may be displayed in plaintext in CloudTrail logs and other output.
	//
	// Tagging or untagging a KMS key can allow or deny permission to the KMS key.
	// For details, see ABAC for KMS (https://docs.aws.amazon.com/kms/latest/developerguide/abac.html)
	// in the Key Management Service Developer Guide.
	//
	// To use this parameter, you must have kms:TagResource (https://docs.aws.amazon.com/kms/latest/developerguide/kms-api-permissions-reference.html)
	// permission in an IAM policy.
	//
	// Tags are not a shared property of multi-Region keys. You can specify the
	// same tags or different tags for each key in a set of related multi-Region
	// keys. KMS does not synchronize this property.
	Tags []*Tag `json:"tags,omitempty"`
}

// ReplicaKeyStatus defines the observed state of ReplicaKey
type ReplicaKeyStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The twelve-digit account ID of the Amazon Web Services account that owns
	// the replica key.
	// +kubebuilder:validation:Optional
	AWSAccountID *string `json:"awsAccountID,omitempty"`
	// The date and time when the replica key was created.
	// +kubebuilder:validation:Optional
	CreationDate *metav1.Time `json:"creationDate,omitempty"`
	// The date and time after which KMS deletes this replica key. This value is
	// present only when the replica key is scheduled for deletion.
	// +kubebuilder:validation:Optional
	DeletionDate *metav1.Time `json:"deletionDate,omitempty"`
	// Specifies whether the replica key is enabled. When KeyState is Enabled this
	// value is true, otherwise it is false.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty"`
	// The encryption algorithms that the replica key supports.
	// +kubebuilder:validation:Optional
	EncryptionAlgorithms []*string `json:"encryptionAlgorithms,omitempty"`
	// The globally unique identifier for the replica key.
	// +kubebuilder:validation:Optional
	KeyID *string `json:"keyID,omitempty"`
	// The current status of the replica key.
	//
	// For more information about how key state affects the use of a KMS key, see
	// Key states of KMS keys (https://docs.aws.amazon.com/kms/latest/developerguide/key-state.html)
	// in the Key Management Service Developer Guide.
	// +kubebuilder:validation:Optional
	KeyState *string `json:"keyState,omitempty"`
	// The message authentication code (MAC) algorithm that the HMAC replica key supports.
	// +kubebuilder:validation:Optional
	MacAlgorithms []*string `json:"macAlgorithms,omitempty"`
	// Lists the primary and replica keys in same multi-Region key.
	// +kubebuilder:validation:Optional
	MultiRegionConfiguration *MultiRegionConfiguration `json:"multiRegionConfiguration,omitempty"`
	// The signing algorithms that the replica key supports.
	// +kubebuilder:validation:Optional
	SigningAlgorithms []*string `json:"signingAlgorithms,omitempty"`
}

// ReplicaKey is the Schema for the ReplicaKeys API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="KeyID",type=string,JSONPath=`.status.keyID`
// +kubebuilder:printcolumn:name="Region",type=string,JSONPath=`.spec.replicaRegion`
// +kubebuilder:printcolumn:name="State",type=string,JSONPath=`.status.keyState`
type ReplicaKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ReplicaKeySpec   `json:"spec,omitempty"`
	Status            ReplicaKeyStatus `json:"status,omitempty"`
}

// ReplicaKeyList contains a list of ReplicaKey
// +kubebuilder:object:root=true
type ReplicaKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReplicaKey `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ReplicaKey{}, &ReplicaKeyList{})
}
